export const PLATFORM_TYPES = [
    "Guest Post",
    "Niche Edit",
    "Blog",
    "News / Magazine",
    "Web 2.0",
    "Forum",
    "Business Directory",
    "Social Bookmarking",
    "Profile Creation",
    "PBN",
    "EDU",
    "GOV",
    "Press Release",
    "Q&A Site",
    "Coupon Site",
    "Review Site",
    "SaaS Listing",
    "Resource Page",
    "eCommerce Listing"
];

export const CATEGORIES = [
    "Business",
    "Marketing",
    "Digital Marketing",
    "SEO",
    "Finance",
    "Investment",
    "Insurance",
    "Cryptocurrency",
    "Technology",
    "Software",
    "Programming",
    "AI / Machine Learning",
    "Web Development",
    "Cybersecurity",
    "Travel",
    "Tourism",
    "Hotels & Hospitality",
    "Real Estate",
    "Home Improvement",
    "Interior Design",
    "DIY",
    "Health",
    "Fitness",
    "Wellness",
    "Nutrition",
    "Mental Health",
    "Medical",
    "Dental",
    "Skincare",
    "Lifestyle",
    "Parenting",
    "Education",
    "Online Learning",
    "Food & Cooking",
    "Recipes",
    "Restaurants",
    "Fashion",
    "Beauty",
    "Sports",
    "Gaming",
    "Entertainment",
    "Automotive",
    "Car Reviews",
    "Auto Repair",
    "Pets & Animals",
    "Photography",
    "Legal / Law",
    "Casino / Gambling",
    "CBD / Cannabis",
    "E-Commerce",
    "Reviews",
    "Startup",
    "Entrepreneurship"
];